project_name/authentication/urls.py
from django.urls import path

from {{ project_name }}.authentication.views import login_view, logout_view

app_name = 'auth'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

project_name/authentication/models.py
from {{ project_name }}.authentication.managers import CustomUserManager
from django.contrib.auth.models import AbstractUser, Group
from django.db import models


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class CustomGroup(Group):
    """Created only to group apps in administrator"""
    class Meta:
        proxy = True
        verbose_name = "Group"
        verbose_name_plural = "Groups"

project_name/core/models.py
from django.db import models

# Create your models here.

project_name/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from {{ project_name }}.authentication.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class LoginForm(forms.Form):
    email = forms.EmailField()
    senha = forms.CharField(max_length=30, widget=forms.PasswordInput)

project_name/authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse

from {{ project_name }}.authentication.forms import LoginForm


def login_view(request):
    if request.method == 'GET':
        return _login_view_get(request)
    else:
        return _login_view_post(request)


def _login_view_get(request):
    form = LoginForm()
    context = dict(form=form)
    return render(request, 'authentication/login.html', context)


def _login_view_post(request):
    form = LoginForm(request.POST)
    if not form.is_valid():
        context = dict(form=form)
        return render(request, 'authentication/login.html', context=context, status=403)
    email = form.cleaned_data.get('email')
    senha = form.cleaned_data.get('senha')
    user = authenticate(email=email, password=senha)
    if user is None:
        context = dict(form=form)
        return render(request, 'authentication/login.html', context=context, status=403)
    login(request, user)
    next_url = request.GET.get('next', '/')
    return redirect(next_url)



def logout_view(request):
    logout(request)
    return redirect(reverse('auth:login'))

project_name/core/views.py
from django.shortcuts import render

# Create your views here.

project_name/authentication/templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="dns-prefetch" href="//recyplus.com.br">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://code.jquery.com">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Recyplus</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'new/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'new/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
    <nav class="white lighten-1" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo"><img src="{% static 'new/img/logo.png' %}"/></a>
          <ul class="blue right hide-on-med-and-down">
            <li><a href="#">Recicla Kids</a></li>
            <li><a href="#">Entrar</a></li>
          </ul>
    
          <ul id="nav-mobile" class="sidenav">
            <li><a href="#">Recicla Kids</a></li>
            <li><a href="#">Entrar</a></li>
          </ul>
          <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
      </nav>

<div class="container">
      
  <div class="row">

    <div class="col s8 offset-s2">

        <div class="card-content">
            
          <span class="card-title">Digite seu usuário e senha para continuar</span>
          <form data-form-type="login" method="post">
          {% csrf_token %}
            <div class="input-field">
              {{ form.email }}
              <label for="id_email">E-mail</label>
            </div>
            <div class="input-field">
              {{ form.senha }}
              <label for="id_senha">Senha</label>
            </div>

            <a href="#!">Esqueceu a senha?</a>

            <br><br>
            <div>
              <input class="btn right green" type="submit" value="Log In" >
              <a href="{% url 'core:site' %}" class="btn-flat right">Voltar</a>
            </div>

          </form>
        </div>
      </div>

    </div>
  </div>
</div>

  <footer class="page-footer blue">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Recyplus </h5>
          <p class="grey-text text-lighten-4">Recyplus é  um produto da Ambientalíssima.  </p>
          <p class="grey-text text-lighten-4">Somos uma equipe focada em gestão de resíduos sólidos....</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Nossos Programas</h5>
          <ul>
            <li><a class="white-text" href="#!">Recicla Kids</a></li>
            <li><a class="white-text" href="#!">Recicla Condomínios</a></li>
            <li><a class="white-text" href="#!">Recicla Empresarial</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Siga-nos</h5>
          <ul>
            <li><a class="white-text" href="#!">Instagram</a></li>
            <li><a class="white-text" href="#!">Facebook</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Desenvolvido por <a class="orange-text text-lighten-3" href="https://manus.inf.br?utm_source='recyplus'">Manu's Informática</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'new/js/materialize.js' %}"></script>
  <script src="{% static 'new/js/init.js' %}"></script>

  </body>
</html>